/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Validates a ULID string.
 * Returns true if the string is a valid ULID, false otherwise.
 * example
 * ```js
 * isValid(01ARYZ6S41TSV4RRFFQ69G5FAV) // true
 * isValid(01ARYZ6S41TSV4RRFFQ69G5FA) // false because length is not 26
 * ```
 */
export declare function isValid(id: string): boolean
/** Decodes a ULID string and returns the unix timestamp. */
export declare function decodeTime(id: string): number
/** Generates a new ULID string. */
export declare function ulid(): string
